# Generated by Django 5.1.3 on 2025-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bogieDetails', models.JSONField()),
                ('bogieChecksheet', models.JSONField()),
                ('bmbcChecksheet', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
